defaults:
  - env/train: libero_spatial
  - env/eval: libero_spatial
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor,env,rollout: all

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "test_openvla"
    logger_backends: ["tensorboard"] # wandb, swanlab

  max_epochs: 1000
  max_steps: -1

  only_eval: False
  val_check_interval: -1
  save_interval: 100
  seq_length: 4096
  max_prompt_length: 30

algorithm:
  auto_reset: False
  ignore_terminations: False
  use_fixed_reset_state_ids: True
  normalize_advantages: True
  kl_penalty: kl  # how to estimate kl divergence: kl or kl_penalty
  group_size: 1
  max_episode_steps: 240
  use_ordered_reset_state_ids: False
  reward_coef: 1.0
  n_chunk_steps: ${int_div:${env.train.max_episode_steps}, ${actor.model.num_action_chunks}}
  n_eval_chunk_steps: ${int_div:${env.train.max_episode_steps}, ${actor.model.num_action_chunks}}
  num_group_envs: 64
  rollout_epoch: 4
  reward_type: chunk_level
  logprob_type: chunk_level
  entropy_type: chunk_level

  update_epoch: 1
  adv_type: embodied_gae
  loss_type: embodied_ppo
  loss_agg_func: "token-mean" 
  kl_beta: 0.0
  entropy_bonus: 0
  clip_ratio_high: 0.2
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 0.2
  huber_delta: 10.0

  gamma: 0.99
  gae_lambda: 0.95

  filter_rewards: False
  rewards_lower_bound: 0.1
  rewards_upper_bound: 0.9
  # params for generation
  sampling_params:
    use_greedy: False
    temperature_train: 1.0
    temperature_eval: 0.6
    top_k: 50
    top_p: 1.0
    repetition_penalty: 1.0
    add_BOS: False

  # length argument for autoregressive sampling
  # max length means max amount of tokens to generate
  length_params:
    max_new_token: null
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  channel:
    name: "env_buffer_list"
    queue_name: "obs_buffer"
    queue_size: 0
  enable_offload: False

rollout:
  group_name: "RolloutGroup"
  channel:
    name: ${env.channel.name}
    queue_name: "action_buffer"
    queue_size: 0
  mode: "colocate"
  backend: "huggingface"
  model_dir: "/root/gr00t_libero_spatial"
  enable_offload: True
  pipeline_stage_num: 1

actor:
  group_name: "ActorGroup"
  channel:
    name: ${env.channel.name}
    queue_name: "replay_buffer"
    queue_size: 0
  training_backend: "fsdp"
  checkpoint_load_path: "/root/gr00t_libero_spatial"
  checkpoint_save_path: "../results"
  micro_batch_size: 128
  global_batch_size: 1024
  seed: 1234
  enable_offload: False

  model:
    precision: "bf16"
    trust_remote_code: True
    is_lora: false
    model_name: "gr00t"
    action_dim: 7
    num_action_chunks: 5
    denoising_steps: 4
    policy_setup: "widowx_bridge"
    obs_converter_type: "libero"
    embodiment_tag: "new_embodiment"
    use_wrist_image: True
    rl_head_config:
      joint_logprob: False
      noise_method: "flow_sde"
      ignore_last: False
      safe_get_logprob: False
      noise_anneal: False
      noise_params: [0.7, 0.3, 400]
      noise_level: 0.5
      add_value_head: True
      chunk_critic_input: False
      detach_critic_input: True
      valid_action_dim: 7
      disable_dropout: False

  optim:
    lr: 2.0e-5
    value_lr: 2.0e-5
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-05
    clip_grad: 1.0
  
  fsdp_config:
    use_orig_params: False

reward:
  use_reward_model: False

critic:
  use_critic_model: False