defaults:
  - env/train: PickCube
  - env/eval: PickCube
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor: 2-2
    env: 2-2
    rollout: 2-2

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "test_openvla"
    logger_backends: ["tensorboard"] # wandb, swanlab

  max_epochs: 1000
  max_steps: -1

  only_eval: False
  val_check_interval: 50
  save_interval: -1
  seq_length: 4096
  max_prompt_length: 30

algorithm:
  update_epoch: 8
  auto_reset: True
  ignore_terminations: False
  use_fixed_reset_state_ids: False
  normalize_advantages: True
  obs_mode: rgb
  kl_penalty: kl  # how to estimate kl divergence: kl or kl_penalty
  group_size: 1
  n_chunk_steps: 100
  n_eval_chunk_steps: 50
  num_group_envs: 1024
  rollout_epoch: 1
  reward_type: action_level
  logprob_type: action_level
  entropy_type: action_level

  adv_type: gae
  loss_type: actor_critic
  loss_agg_func: "token-mean"
  kl_beta: 0.0
  entropy_bonus: 0
  clip_ratio_high: 0.2
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 1.0
  huber_delta: 10.0

  gamma: 0.8
  gae_lambda: 0.9

  # params for rollout
  sampling_params:
    use_greedy: False
    temperature_train: 1.0
    temperature_eval: 0.6
    top_k: 0
    top_p: 1.0
    repetition_penalty: 1.0

  # length argument for autoregressive sampling
  # max length means max amount of tokens to generate
  length_params:
    max_new_token: 7
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  channel:
    name: "env_buffer_list"
    queue_name: "obs_buffer"
    queue_size: 0
  enable_offload: False

rollout:
  group_name: "RolloutGroup"
  channel:
    name: ${env.channel.name}
    queue_name: "action_buffer"
    queue_size: 0
  mode: "colocate"
  backend: "huggingface"
  model_dir: ""
  enable_offload: False
  pipeline_stage_num: 1

actor:
  group_name: "ActorGroup"
  channel:
    name: ${env.channel.name}
    queue_name: "replay_buffer"
    queue_size: 0
  training_backend: "fsdp"
  checkpoint_load_path: ""
  checkpoint_save_path: "../results"
  micro_batch_size: 1600
  global_batch_size: 1600
  seed: 1234
  enable_offload: False

  model:
    model_name: "cnn"
    policy_setup: "panda-ee-dpos"
    image_keys: ["base_camera", ]
    image_size: [3, 64, 64]
    state_dim: 29
    action_dim: 4
    num_action_chunks: 1
    hidden_dim: 256
    
    precision: "32"
    add_value_head: True
    add_q_head: False
    backbone: resnet # ["resnet", "plane_conv"]
    
    is_lora: False
    lora_rank: 32
    ckpt_path: null
    gradient_checkpointing: False
    sharding_strategy: no_shard
    vh_mode: "q_network"
    q_network_separate_processing: True

  extra_config:
      pretrained_ckpt_path: "./resnet10_pretrained.pt"
  
  optim:
    lr: 3.0e-4
    value_lr: 3.0e-4
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_eps: 1.0e-05
    clip_grad: 0.5

  fsdp:
    forward_prefetch: False
    limit_all_gathers: False
    backward_prefetch: False
    use_orig_params: True

reward:
  use_reward_model: False

critic:
  use_critic_model: False