defaults:
  - env/mujoco_pickcube_state@env.train
  - env/mujoco_pickcube_state@env.eval
  - model/mlp_policy@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor: 0-0
    env: 0-0
    rollout: 0-0

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "serl_ppo_mlp_pandapickcube_state"
    logger_backends: ["tensorboard"]

  max_epochs: 500
  max_steps: -1

  only_eval: False
  eval_policy_path: null
  val_check_interval: 50
  save_interval: -1

  # 对 MLP policy 不重要，但框架需要
  seq_length: 1
  max_prompt_length: 1

  resume_dir: null

algorithm:
  update_epoch: 8
  normalize_advantages: True
  kl_penalty: kl
  group_size: 1

  rollout_epoch: 1
  eval_rollout_epoch: 1

  reward_type: action_level
  logprob_type: action_level
  entropy_type: action_level

  adv_type: gae
  loss_type: actor_critic
  loss_agg_func: "token-mean"

  kl_beta: 0.0
  entropy_bonus: 0
  clip_ratio_high: 0.2
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 1.0
  huber_delta: 10.0

  gamma: 0.99
  gae_lambda: 0.95

  sampling_params:
    do_sample: True
    temperature_train: 1.0
    temperature_eval: 0.6
    top_k: 0
    top_p: 1.0
    repetition_penalty: 1.0

  length_params:
    max_new_token: 1
    max_length: 1
    min_length: 1

env:
  group_name: "EnvGroup"
  enable_offload: False
  device: cpu
  mujoco_gl: disable
  
  train:
    total_num_envs: 128
    auto_reset: True
    ignore_terminations: False
    max_episode_steps: 200
    max_steps_per_rollout_epoch: 200
    group_size: 1

  eval:
    total_num_envs: 16
    auto_reset: True
    ignore_terminations: True
    max_episode_steps: 200
    max_steps_per_rollout_epoch: 200
    use_fixed_reset_state_ids: False
    group_size: 1
    video_cfg:
      save_video: False
      

rollout:
  group_name: "RolloutGroup"
  backend: "huggingface"
  enable_offload: False
  pipeline_stage_num: 1
  device: cpu
  model:
    model_path: ""
    precision: ${actor.model.precision}

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 256
  global_batch_size: 256
  seed: 1234
  enable_offload: False
  device: cuda
  model:
    model_path: ""
    model_type: "mlp_policy"
    obs_dim: 10
    

  optim:
    lr: 3.0e-4
    value_lr: 3.0e-4
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_eps: 1.0e-05
    weight_decay: 0.01
    clip_grad: 0.5

  fsdp_config:
    strategy: "fsdp"
    sharding_strategy: "no_shard"
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: False

critic:
  use_critic_model: False

