defaults:
  - env/robotwin_click_bell@env.train
  - env/robotwin_click_bell@env.eval
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null 
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/
    
cluster:
  num_nodes: 1
  component_placement:
    rollout: 0-3
    env: 4-7
    actor: 0-3

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "eval_lingbot_click_bell"
    logger_backends: ["tensorboard"]

  max_epochs: 1
  max_steps: -1
  only_eval: True
  eval_episodes: 100        
  val_check_interval: -1
  save_interval: 100
  resume_dir: null
  ckpt_path: null

algorithm:
  normalize_advantages: True
  kl_penalty: kl
  group_size: 1
  rollout_epoch: 1
  eval_rollout_epoch: 1
  reward_type: chunk_level
  logprob_type: token_level
  entropy_type: token_level
  adv_type: gae
  loss_type: actor_critic
  loss_agg_func: "token-mean"
  kl_beta: 0.0
  entropy_bonus: 0
  clip_ratio_high: 0.28
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 0.2
  huber_delta: 10.0
  gamma: 0.99
  gae_lambda: 0.95
  sampling_params:
    do_sample: False
    temperature_train: 1.6
    temperature_eval: -1
    top_k: -1
    top_p: 1.0
    repetition_penalty: 1.0
  length_params:
    max_new_token: null
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  eval:
    total_num_envs: 20
    auto_reset: True
    ignore_terminations: True
    max_episode_steps: 300
    max_steps_per_rollout_epoch: 300
    group_size: 1
    use_fixed_reset_state_ids: True
    is_eval: True
    video_cfg:
      save_video: True
      video_base_dir: /mnt/public/lwb/work/RLinf/RoboTwin/eval_result/click_bell/policy.lingbot_wrapper/demo_clean
  train:
    total_num_envs: 4
    group_size: 1
    max_steps_per_rollout_epoch: 300

rollout:
  group_name: "RolloutGroup"
  backend: "huggingface"
  enable_offload: False
  pipeline_stage_num: 1
  model:
    model_type: "lingbot"
    model_path: /mnt/public/lwb/test_project/lingbot-vla/output_click_bell_aloha/checkpoints/global_step_8280/hf_ckpt
    tokenizer_path: /mnt/public/lwb/test_project/lingbot-vla/Qwen2.5-VL-3B-Instruct
    action_dim: 14
    num_action_chunks: 50
    precision: "bf16"
    is_lora: False

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 1
  global_batch_size: 4
  seed: 1234
  enable_offload: True
  model:
    model_type: "lingbot"
    model_path: /mnt/public/lwb/test_project/lingbot-vla/output_click_bell_aloha/checkpoints/global_step_8280/hf_ckpt
    tokenizer_path: /mnt/public/lwb/test_project/lingbot-vla/Qwen2.5-VL-3B-Instruct
    action_dim: 14
    num_action_chunks: 50
    add_value_head: True
    precision: "bf16"
    is_lora: False
  optim:
    lr: 1.0e-4
    value_lr: 3.0e-3
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_eps: 1.0e-05
    clip_grad: 10.0
  fsdp_config:
    strategy: "fsdp"
    gradient_checkpointing: False
    mixed_precision:
      param_dtype: "bf16"
      reduce_dtype: "bf16"
      buffer_dtype: "fp32"

critic:
  use_critic_model: False