defaults:
  - env/robotwin_click_bell@env.train
  - env/robotwin_click_bell@env.eval
  - model/lingbot@actor.model          
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/
    
cluster:
  num_nodes: 1
  component_placement:
    actor, rollout: 0-3
    env: 4-7

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "robotwin_grpo_lingbot"
    logger_backends: ["tensorboard"]

  max_epochs: 1000
  max_steps: -1

  only_eval: False
  val_check_interval: 10
  save_interval: 10

  resume_dir: null
  ckpt_path: null

algorithm:
  normalize_advantages: True
  kl_penalty: kl
  group_size: 2

  rollout_epoch: 8
  eval_rollout_epoch: 1

  reward_type: action_level
  logprob_type: token_level
  entropy_type: token_level

  adv_type: grpo
  loss_type: actor
  loss_agg_func: "token-mean"
  kl_beta: 0.0
  entropy_bonus: 0
  clip_ratio_high: 0.28
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 0.2
  huber_delta: 10.0

  gamma: 1.0
  gae_lambda: 0.95

  reward_coef: 5.0
  filter_rewards: True
  rewards_lower_bound: 0.5
  rewards_upper_bound: 4.5

  sampling_params:
    do_sample: True
    temperature_train: 1.6
    temperature_eval: -1
    top_k: -1
    top_p: 1.0
    repetition_penalty: 1.0

  length_params:
    max_new_token: null
    max_length: 512
    min_length: 1

env:
  group_name: "EnvGroup"
  train:
    total_num_envs: 16    
    reward_coef: ${algorithm.reward_coef}
    max_episode_steps: 200
    max_steps_per_rollout_epoch: 200
    group_size: ${algorithm.group_size}
    assets_path: "/mnt/public/lwb/work/RLinf/RoboTwin"
    seeds_path: ${oc.env:REPO_PATH}/rlinf/envs/robotwin/seeds/train_seeds.json
    enable_offload: True

  eval:
    total_num_envs: 16    
    auto_reset: True
    ignore_terminations: True
    max_episode_steps: 200
    reward_coef: ${algorithm.reward_coef}
    max_steps_per_rollout_epoch: 200
    group_size: 1
    use_fixed_reset_state_ids: True
    is_eval: True
    assets_path: "/mnt/public/lwb/work/RLinf/RoboTwin"
    seeds_path: ${oc.env:REPO_PATH}/rlinf/envs/robotwin/seeds/eval_seeds.json
    video_cfg:
      save_video: True
      video_base_dir: ${runner.logger.log_path}/video/eval
    enable_offload: True

rollout:
  group_name: "RolloutGroup"
  backend: "huggingface"
  enable_offload: True
  pipeline_stage_num: 2
  model:
    model_type: "lingbot"
    model_path: ${actor.model.model_path}
    precision: ${actor.model.precision}

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 1     
  global_batch_size: 16   
  seed: 1234
  enable_offload: True

  optim:
    lr: 1.0e-4
    value_lr: 1.0e-5
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_eps: 1.0e-05
    weight_decay: 0.01
    clip_grad: 1.0

  fsdp_config:
    strategy: "fsdp"
    gradient_checkpointing: True
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: False

critic:
  use_critic_model: False
