simulator_type: real
auto_reset: ${algorithm.auto_reset}
ignore_terminations: ${algorithm.ignore_terminations}
use_rel_reward: True
reward_mode: raw
seed: 0
num_group: ${algorithm.num_group_envs}
group_size: ${algorithm.group_size}
use_fixed_reset_state_ids: ${algorithm.use_fixed_reset_state_ids}
max_episode_steps: 100
only_eval: False
num_envs: ${multiply:${algorithm.group_size}, ${algorithm.num_group_envs}}

robot_ip: null
camera_serials: null

video_cfg:
  save_video: True
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/train

init_params:
  id: "PegInsertionEnv-v1"
  num_envs: ${env.train.num_envs}
  control_mode: None
  sim_backend: "gpu"
  sim_config:
    sim_freq: 100
    control_freq: 20
  max_episode_steps: ${env.train.max_episode_steps}
  sensor_configs:
    shader_pack: "default"
    width: 128
    height: 128
  render_mode: all
