simulator_type: rlbench
task_names: ["ReachTarget", "CloseBox", "CloseMicrowave", "PlugChargerInPowerSupply", "ToiletSeatDown", "TakeUmbrellaOutOfUmbrellaStand", "PutUmbrellaInUmbrellaStand", "SlideCabinetOpen", "CloseFridge", "PickAndLift"] # MT15_V1

auto_reset: ${algorithm.auto_reset}
ignore_terminations: ${algorithm.ignore_terminations}
max_episode_steps: ${algorithm.max_episode_steps}

use_rel_reward: False
reward_coef: ${algorithm.reward_coef}
only_eval: False

seed: 0
num_group: ${algorithm.num_group_envs}
group_size: ${algorithm.group_size}
use_fixed_reset_state_ids: ${algorithm.use_fixed_reset_state_ids}

num_envs: ${multiply:${algorithm.group_size}, ${algorithm.num_group_envs}}

image_size: [128, 128]
save_video: True
video_base_dir: ${runner.logger.log_path}/video/train

init_params:
  robot_setup: "panda"  # Options: "panda", "franka", etc.

