defaults:
  - mas_train

cluster:
  num_nodes: 1
  component_placement:
    actor,rollout,reward: all

runner:
  experiment_name: main4b_sub7b
  output_dir: /mnt/project_rlinf/zhuchunyang_rl/logs
  seq_length: 15000  

  enable_dynamic_batch_size: True
  max_tokens_per_mbs: 15000

  max_epochs: 1
  max_steps: -1

algorithm:
  group_size: 8
  n_minibatches: 1


agentloop:
  use_llm_judge_api: True
  workflow: mas


rollout:
  use_sub_worker: True 
  gpu_memory_utilization: 0.6
  model:
    model_type: qwen3
    model_path: /mnt/public/xzxuan/model/Qwen3-4B
  tensor_parallel_size: 1
  pipeline_parallel_size: 1

rollout_sub_worker:
  gpu_memory_utilization: 0.6
  model:
    model_type: qwen2.5
    model_path: /mnt/public/hf_models/Qwen2.5-3B-Instruct-search
  tensor_parallel_size: 1
  pipeline_parallel_size: 1

tools:
  online: False


data:
  type: mas
  max_prompt_length: 4096
  # rollout_batch_size: 128
  rollout_batch_size: 16
  train_data_paths: ["/mnt/public/xzxuan/data/nq_hotpotqa_train/train_RLinf.jsonl"]
  val_data_paths: ["/mnt/public/xzxuan/data/nq_hotpotqa_train/train_RLinf.jsonl"]

actor:
  model:
    megatron_checkpoint: /mnt/public/xzxuan/Multi-Agent/RLinf/converted_ckpts/qwen3_4b_tp1_pp1
    recompute_num_layers: 36

    tensor_model_parallel_size: 1
    pipeline_model_parallel_size: 1
    sequence_parallel: False
    # sequence_parallel: ${gt:${actor.model.tensor_model_parallel_size}, 1}

  megatron:
    use_hf_ckpt: False  
    ckpt_convertor:
      model: Qwen3-4B

reward:
  reward_type: 'em' # or em
  eval_metric: []  
