simulator_type: maniskill
auto_reset: True
ignore_terminations: True
use_rel_reward: True
seed: 0
num_group: ${algorithm.num_group_envs}
group_size: ${algorithm.group_size}
use_fixed_reset_state_ids: True
only_eval: True
num_envs: ${multiply:${algorithm.group_size}, ${algorithm.num_group_envs}}
video_cfg:
  save_video: True
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/eval

init_params:
  id: PandaPutOnPlateInScene25Simple-v1
  num_envs: ${multiply:${algorithm.group_size}, ${algorithm.num_group_envs}}
  obs_mode: ${env.train.init_params.obs_mode}
  control_mode: pd_ee_body_target_delta_pose_real_root_frame
  sim_backend: "gpu"
  sim_config: ${env.train.init_params.sim_config}
  max_episode_steps: ${env.train.init_params.max_episode_steps}
  sensor_configs: ${env.train.init_params.sensor_configs}
  render_mode: rgb_array
  reward_mode: normalized_dense
  use_curriculum: false