defaults:
  - base_eval

cluster:
  num_nodes: 1
  component_placement:
    actor,rollout,reward: all

runner:
  experiment_name: eval-qa-dbg
  output_dir: /mnt/project_rlinf/zhuchunyang_rl/logs
  seq_length: 8192  

  max_epochs: 1
  max_steps: -1  

algorithm:
  group_size: 4

agentloop:
  use_llm_judge_api: True
  workflow: mas
  max_planner_turns: 2
  max_worker_turns: 2

rollout:
  model:
    model_type: qwen3
    model_path: /mnt/project_rlinf/xzxuan/model/Qwen3-4B
  tensor_parallel_size: 1
  pipeline_parallel_size: 1


tools:
  online: False

data:
  type: wideseek_r1
  max_prompt_length: 4096
  val_rollout_batch_size: 1000
  prompt_key: question
  answer_key: answer
  is_markdown: False
  val_data_paths: ["/mnt/project_rlinf/xzxuan/data/Asearcher-test-data/Bamboogle/test.jsonl"] # TODO:
  validation_shuffle: True
  data_size: -1

reward:
  reward_type: 'llm' # or em
  eval_metric: ['em', 'f1', 'llm']


