defaults:
  - model/pi0_5@model
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:REPO_PATH}/examples/embodiment/config

convertor:
  save_path: /path/to/fsdp_checkpoint_dir
  merge_lora_weighs: False
  ckpt_path: /path/to/fsdp_checkpoint_dir/full_weights.pt

model:
  model_type: "cfg_model"
  model_path: "/path/to/pi05_base_pytorch"

  openpi:
    action_chunk: 10
    num_steps: 5
    action_env_dim: 7
    add_value_head: False

  is_lora: False
