env_type: droid
total_num_envs: null
auto_reset: False
ignore_terminations: False
use_rel_reward: True
seed: 0
group_size: 1

reward_coef: 1.0
use_fixed_reset_state_ids: False
max_steps_per_rollout_epoch: 256
max_episode_steps: 256

video_cfg:
  save_video: False
  info_on_video: True
  fps: 20
  video_base_dir: ${runner.logger.log_path}/video/train

init_params:
  scene: 1
  device: "cuda:0"
  task_description: "put the cube in the bowl"
  headless: True
  warmup_reset: True
