env_type: habitat

seed: 0
group_size: 1
reward_coef: 5.0
use_rel_reward: True
total_num_envs: null
auto_reset: False
ignore_terminations: False
max_steps_per_rollout_epoch: 200
max_episode_steps: 200

init_params:
  config_path: "path/to/config" # Select in the rlinf/envs/habitat/extensions/config folder