simulator_type: mixed
simulator_list:
  - simulator_type: libero
    task_suite_name: libero_spatial
    init_params:
      camera_heights: 256
      camera_widths: 256

    unnorm_key: libero_130_no_noops_trajall  # unnorm_key for libero environment
    unnorm_key_file: "/mnt/mnt/public/hyx/sft2/openvla-oft/ckpts/8vs2/openvla-7b+libero_130_no_noops_trajall_maniskill+b8+lr-0.0005+lora-r32+dropout-0.0--image_aug--10000_chkpt/dataset_statistics.json"

  - simulator_type: maniskill
    policy_setup: "widowx_bridge"
    init_params:
      id: "PutOnPlateInScene25Main-v3"
      num_envs: null # will be set in ManiSkillEnv init
      obs_mode: "rgb+segmentation"
      control_mode: None
      sim_backend: "gpu"
      sim_config:
        sim_freq: 500
        control_freq: 5
      max_episode_steps: 80 # max episode steps for truncation
      sensor_configs:
        shader_pack: "default"
      render_mode: all
      obj_set: train

    unnorm_key: maniskill  # unnorm_key for maniskill environment
    unnorm_key_file: "/mnt/mnt/public/hyx/sft2/openvla-oft/ckpts/8vs2/openvla-7b+libero_130_no_noops_trajall_maniskill+b8+lr-0.0005+lora-r32+dropout-0.0--image_aug--10000_chkpt/dataset_statistics.json"

total_num_envs: null

auto_reset: False
ignore_terminations: False
max_steps_per_rollout_epoch: 512
max_episode_steps: 512 # max episode steps for truncation

use_rel_reward: True
reward_coef: 1.0
is_eval: False

seed: 0
group_size: 1
use_fixed_reset_state_ids: True
use_ordered_reset_state_ids: True

video_cfg:
  save_video: True
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/train
