env_type: rlbench
simulator_type: rlbench
image_size: [128, 128]
task_names: ["ReachTarget", "CloseBox", "CloseMicrowave", "PlugChargerInPowerSupply", "ToiletSeatDown", "TakeUmbrellaOutOfUmbrellaStand", "PutUmbrellaInUmbrellaStand", "SlideCabinetOpen", "CloseFridge", "PickAndLift"] # MT15_V1

total_num_envs: null

auto_reset: False
ignore_terminations: False
max_steps_per_rollout_epoch: 200
max_episode_steps: 200 # max episode steps for truncation

use_rel_reward: True
reward_coef: 1.0
is_eval: False

seed: 0
group_size: 1
use_fixed_reset_state_ids: False
use_ordered_reset_state_ids: False

video_cfg:
  save_video: False
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/train

# Action flow aligned with Metaworld: no env-side clipping; policy outputs unnormalized action (openpi Unnormalize).

init_params:
  robot_setup: "panda"  # Options: "panda", "franka", etc.
